# Generated by Django 6.0.2 on 2026-02-19

from django.db import migrations


BASE_ROLES = [
    {
        "name": "مدیر کل سامانه",
        "description": "System-wide administrator with role management access.",
        "default_flags": {
            "is_system_admin": True,
            "can_manage_roles": True,
        },
    },
    {
        "name": "رئیس پلیس",
        "description": "Police chief with high-level operational access.",
        "default_flags": {"can_manage_operations": True},
    },
    {
        "name": "کاپیتان",
        "description": "Captain role for team leadership tasks.",
        "default_flags": {"can_lead_team": True},
    },
    {
        "name": "گروهبان",
        "description": "Sergeant role for field supervision.",
        "default_flags": {"can_supervise_field_units": True},
    },
    {
        "name": "کارآگاه",
        "description": "Detective role focused on investigations.",
        "default_flags": {"can_investigate_cases": True},
    },
    {
        "name": "مامور پلیس و افسر گشت",
        "description": "Patrol officer role for on-site enforcement activities.",
        "default_flags": {"can_patrol": True},
    },
    {
        "name": "کارآموز",
        "description": "Intern role with limited training-level access.",
        "default_flags": {"training_only": True},
    },
    {
        "name": "شاکی و شاهد",
        "description": "Complainant and witness external-facing role.",
        "default_flags": {"external_participant": True},
    },
    {
        "name": "متهم و مجرم",
        "description": "Accused/criminal role for legal workflow references.",
        "default_flags": {"restricted_profile": True},
    },
    {
        "name": "قاضی",
        "description": "Judge role for judicial case interactions.",
        "default_flags": {"judicial_access": True},
    },
    {
        "name": "پزشک قانونی",
        "description": "Forensic doctor role for medical/legal reports.",
        "default_flags": {"can_submit_forensics": True},
    },
    {
        "name": "کاربر پایه",
        "description": "Default role for newly registered users.",
        "default_flags": {"is_default_role": True},
    },
]


def seed_base_roles(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")

    for role_payload in BASE_ROLES:
        Role.objects.update_or_create(
            name=role_payload["name"],
            defaults={
                "description": role_payload["description"],
                "default_flags": role_payload["default_flags"],
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_base_roles, migrations.RunPython.noop),
    ]
