# Generated by Django 6.0.2 on 2026-02-19

from django.db import migrations


ROLE_FLAG_CODE_KEY = "role_code"

ROLE_CODE_SYSTEM_ADMIN = "system_admin"
ROLE_CODE_POLICE_CHIEF = "police_chief"
ROLE_CODE_CAPTAIN = "captain"
ROLE_CODE_SERGEANT = "sergeant"
ROLE_CODE_DETECTIVE = "detective"
ROLE_CODE_POLICE_OFFICER = "police_officer"
ROLE_CODE_PATROL_OFFICER = "patrol_officer"
ROLE_CODE_INTERN = "intern"
ROLE_CODE_COMPLAINANT = "complainant"
ROLE_CODE_WITNESS = "witness"
ROLE_CODE_ACCUSED = "accused"
ROLE_CODE_CRIMINAL = "criminal"
ROLE_CODE_JUDGE = "judge"
ROLE_CODE_FORENSIC_DOCTOR = "forensic_doctor"
ROLE_CODE_BASIC_USER = "basic_user"

BASE_ROLES = [
    {
        "name": "مدیر کل سامانه",
        "description": "System-wide administrator with role management access.",
        "default_flags": {
            ROLE_FLAG_CODE_KEY: ROLE_CODE_SYSTEM_ADMIN,
            "is_system_admin": True,
            "can_manage_roles": True,
        },
    },
    {
        "name": "رئیس پلیس",
        "description": "Police chief with high-level operational access.",
        "default_flags": {
            ROLE_FLAG_CODE_KEY: ROLE_CODE_POLICE_CHIEF,
            "can_manage_operations": True,
        },
    },
    {
        "name": "کاپیتان",
        "description": "Captain role for team leadership tasks.",
        "default_flags": {
            ROLE_FLAG_CODE_KEY: ROLE_CODE_CAPTAIN,
            "can_lead_team": True,
        },
    },
    {
        "name": "گروهبان",
        "description": "Sergeant role for field supervision.",
        "default_flags": {
            ROLE_FLAG_CODE_KEY: ROLE_CODE_SERGEANT,
            "can_supervise_field_units": True,
        },
    },
    {
        "name": "کارآگاه",
        "description": "Detective role focused on investigations.",
        "default_flags": {
            ROLE_FLAG_CODE_KEY: ROLE_CODE_DETECTIVE,
            "can_investigate_cases": True,
        },
    },
    {
        "name": "مامور پلیس",
        "description": "Police officer role for on-site enforcement activities.",
        "default_flags": {
            ROLE_FLAG_CODE_KEY: ROLE_CODE_POLICE_OFFICER,
            "can_patrol": True,
        },
    },
    {
        "name": "افسر گشت",
        "description": "Patrol officer role for field operations.",
        "default_flags": {
            ROLE_FLAG_CODE_KEY: ROLE_CODE_PATROL_OFFICER,
            "can_patrol": True,
        },
    },
    {
        "name": "کارآموز",
        "description": "Intern role with limited training-level access.",
        "default_flags": {
            ROLE_FLAG_CODE_KEY: ROLE_CODE_INTERN,
            "training_only": True,
        },
    },
    {
        "name": "شاکی",
        "description": "Complainant external-facing role.",
        "default_flags": {
            ROLE_FLAG_CODE_KEY: ROLE_CODE_COMPLAINANT,
            "external_participant": True,
        },
    },
    {
        "name": "شاهد",
        "description": "Witness external-facing role.",
        "default_flags": {
            ROLE_FLAG_CODE_KEY: ROLE_CODE_WITNESS,
            "external_participant": True,
        },
    },
    {
        "name": "متهم",
        "description": "Accused role for legal workflow references.",
        "default_flags": {
            ROLE_FLAG_CODE_KEY: ROLE_CODE_ACCUSED,
            "restricted_profile": True,
        },
    },
    {
        "name": "مجرم",
        "description": "Criminal role for legal workflow references.",
        "default_flags": {
            ROLE_FLAG_CODE_KEY: ROLE_CODE_CRIMINAL,
            "restricted_profile": True,
        },
    },
    {
        "name": "قاضی",
        "description": "Judge role for judicial case interactions.",
        "default_flags": {
            ROLE_FLAG_CODE_KEY: ROLE_CODE_JUDGE,
            "judicial_access": True,
        },
    },
    {
        "name": "پزشک قانونی",
        "description": "Forensic doctor role for medical/legal reports.",
        "default_flags": {
            ROLE_FLAG_CODE_KEY: ROLE_CODE_FORENSIC_DOCTOR,
            "can_submit_forensics": True,
        },
    },
    {
        "name": "کاربر پایه",
        "description": "Default role for newly registered users.",
        "default_flags": {
            ROLE_FLAG_CODE_KEY: ROLE_CODE_BASIC_USER,
            "is_default_role": True,
        },
    },
]

LEGACY_COMBINED_ROLE_NAMES = (
    "مامور پلیس و افسر گشت",
    "شاکی و شاهد",
    "متهم و مجرم",
)


def sync_base_roles(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    UserProfile = apps.get_model("accounts", "UserProfile")

    role_by_code = {}
    for role_payload in BASE_ROLES:
        role, _ = Role.objects.get_or_create(
            name=role_payload["name"],
            defaults={
                "description": role_payload["description"],
                "default_flags": role_payload["default_flags"],
            },
        )

        existing_flags = role.default_flags if isinstance(role.default_flags, dict) else {}
        merged_flags = {**existing_flags, **role_payload["default_flags"]}

        update_fields = []
        if role.description != role_payload["description"]:
            role.description = role_payload["description"]
            update_fields.append("description")
        if role.default_flags != merged_flags:
            role.default_flags = merged_flags
            update_fields.append("default_flags")
        if update_fields:
            role.save(update_fields=update_fields)

        role_by_code[role_payload["default_flags"][ROLE_FLAG_CODE_KEY]] = role

    for legacy_name in LEGACY_COMBINED_ROLE_NAMES:
        legacy_role = Role.objects.filter(name=legacy_name).first()
        if legacy_role and not UserProfile.objects.filter(role=legacy_role).exists():
            legacy_role.delete()

    system_admin_role = role_by_code.get(ROLE_CODE_SYSTEM_ADMIN)
    if system_admin_role is not None:
        UserProfile.objects.filter(is_superuser=True, role__isnull=True).update(role=system_admin_role)
        UserProfile.objects.filter(role=system_admin_role, is_staff=False).update(is_staff=True)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_seed_base_roles"),
    ]

    operations = [
        migrations.RunPython(sync_base_roles, migrations.RunPython.noop),
    ]
