# Generated by Django 6.0.2 on 2026-02-21

from django.db import migrations


ROLE_FLAG_CODE_KEY = "role_code"
ROLE_CODE_SYSTEM_ADMIN = "system_admin"


def assign_system_admin_role(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    UserProfile = apps.get_model("accounts", "UserProfile")

    system_admin_role = Role.objects.filter(
        **{f"default_flags__{ROLE_FLAG_CODE_KEY}": ROLE_CODE_SYSTEM_ADMIN}
    ).first()
    if system_admin_role is None:
        system_admin_role = Role.objects.filter(default_flags__is_system_admin=True).first()
    if system_admin_role is None:
        return

    UserProfile.objects.filter(is_superuser=True, role__isnull=True).update(role=system_admin_role)
    UserProfile.objects.filter(is_superuser=True, is_staff=False).update(is_staff=True)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_sync_base_roles_v2"),
    ]

    operations = [
        migrations.RunPython(assign_system_admin_role, migrations.RunPython.noop),
    ]
