# Generated by Django 6.0.2 on 2026-02-22 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('forwarded', 'Forwarded to Detective'), ('confirmed', 'Confirmed — Reward Issued'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('officer_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('officer_notes', models.TextField(blank=True)),
                ('detective_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('detective_notes', models.TextField(blank=True)),
                ('unique_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('reward_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('claimed', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tips', to='cases.case')),
                ('reviewing_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officer_reviewed_tips', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_tips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
