# Generated by Django 6.0.2 on 2026-02-22 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardtip',
            name='suspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tips', to='cases.casesuspect'),
        ),
    ]
