# Generated by Django 6.0.2 on 2026-02-22 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('guilty', 'Guilty'), ('innocent', 'Innocent'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('held_at', models.DateTimeField(blank=True, null=True)),
                ('concluded_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trial', to='cases.case')),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presided_trials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('explanation', models.TextField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('trial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='punishment', to='judiciary.trial')),
            ],
        ),
    ]
