# Generated by Django 6.0.2 on 2026-02-26 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0003_detectiveboardnote_detectiveboardrelation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='detectiveboardnote',
            new_name='investigati_case_id_4449f7_idx',
            old_name='investigatio_case_id_f4e08f_idx',
        ),
        migrations.RenameIndex(
            model_name='detectiveboardrelation',
            new_name='investigati_case_id_42a56d_idx',
            old_name='investigatio_case_id_2877ea_idx',
        ),
        migrations.RenameIndex(
            model_name='investigationaction',
            new_name='investigati_case_id_297089_idx',
            old_name='investigatio_case_id_9df62d_idx',
        ),
        migrations.RenameIndex(
            model_name='investigationaction',
            new_name='investigati_case_id_66b927_idx',
            old_name='investigatio_case_id_317d97_idx',
        ),
    ]
