# Generated by Django 6.0.2 on 2026-02-22 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_remove_casewitness_evidence_casevalidationreview_and_more'),
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonyevidence',
            name='witness',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to='cases.casewitness'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TestimonyMediaFile',
        ),
    ]
