# Generated by Django 6.0.2 on 2026-02-22 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_testimonyevidence_witness_delete_testimonymediafile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonyevidence',
            name='witness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witness_testimonies', to=settings.AUTH_USER_MODEL),
        ),
    ]
