# Generated by Django 6.0.2 on 2026-02-22 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_remove_casewitness_evidence_casevalidationreview_and_more'),
        ('evidence', '0003_alter_testimonyevidence_witness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologicalevidence',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biological_evidences', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='biologicalevidence',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biological_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='identificationdocument',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identification_documents', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='identificationdocument',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identification_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otherevidence',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_evidences', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='otherevidence',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testimonyevidence',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='testimonyevidence',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimony_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicleevidence',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_evidences', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='vehicleevidence',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
