# Generated by Django 6.0.2 on 2026-02-26 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0005_evidenceattachment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='evidenceattachment',
            new_name='evidence_ev_evidenc_cdc7bc_idx',
            old_name='evidence_evi_evidenc_61e26f_idx',
        ),
    ]
