# Generated by Django 6.0.2 on 2026-02-22 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complainant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuspectReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('validated', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('crime_level', models.CharField(choices=[('critical', 'Critical'), ('level_1', 'Level 1'), ('level_2', 'Level 2'), ('level_3', 'Level 3')], max_length=20)),
                ('status', models.CharField(choices=[('awaiting_validation', 'Awaiting Validation'), ('invalidated', 'Invalidated'), ('open', 'Open'), ('under_investigation', 'Under Investigation'), ('awaiting_trial', 'Awaiting Trial'), ('closed', 'Closed')], default='open', max_length=30)),
                ('creation_method', models.CharField(choices=[('complaint', 'Complaint'), ('crime_scene', 'Crime Scene')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_datetime', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=512)),
                ('assigned_detective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detective_cases', to=settings.AUTH_USER_MODEL)),
                ('assigned_sergeant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sergeant_cases', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('validated', models.BooleanField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_review_actions_received', to=settings.AUTH_USER_MODEL)),
                ('destination_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_review_actions_received', to='auth.group')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_review_actions_initiated', to=settings.AUTH_USER_MODEL)),
                ('source_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_review_actions_initiated', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='CaseSuspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confession_transcript', models.TextField(blank=True, null=True)),
                ('detective_guilt_score', models.PositiveSmallIntegerField(blank=True, help_text='Score 1-10 assigned by detective', null=True)),
                ('sergeant_guilt_score', models.PositiveSmallIntegerField(blank=True, help_text='Score 1-10 assigned by sergeant', null=True)),
                ('arrest_status', models.CharField(choices=[('free', 'Free'), ('warrant_issued', 'Warrant Issued'), ('arrested', 'Arrested'), ('released', 'Released')], default='free', max_length=20)),
                ('arrest_warrant_issued_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='cases.case')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspect_in_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseWitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('national_id', models.CharField(max_length=20)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='cases.case')),
            ],
        ),
    ]
