# Generated by Django 6.0.2 on 2026-02-22 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cases', '0001_initial'),
        ('evidence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casewitness',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evidence.testimonyevidence'),
        ),
        migrations.AddField(
            model_name='complainant',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complainants', to='cases.case'),
        ),
        migrations.AddField(
            model_name='complainant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspectreviewaction',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspect_review_actions_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspectreviewaction',
            name='destination_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspect_review_actions_received', to='auth.group'),
        ),
        migrations.AddField(
            model_name='suspectreviewaction',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspect_review_actions_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspectreviewaction',
            name='source_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspect_review_actions_initiated', to='auth.group'),
        ),
        migrations.AlterUniqueTogether(
            name='casesuspect',
            unique_together={('case', 'suspect')},
        ),
        migrations.AlterUniqueTogether(
            name='complainant',
            unique_together={('case', 'user')},
        ),
    ]
