# Generated by Django 6.0.2 on 2026-02-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_remove_casewitness_evidence_casevalidationreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesuspect',
            name='sergeant_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casesuspect',
            name='arrest_status',
            field=models.CharField(choices=[('free', 'Free'), ('awaiting_sergeant', 'Awaiting Sergeant'), ('warrant_issued', 'Warrant Issued'), ('arrested', 'Arrested'), ('awaiting_captain', 'Awaiting Captain'), ('awaiting_chief', 'Awaiting Chief'), ('on_trial', 'On Trial'), ('released', 'Released')], default='free', max_length=20),
        ),
        migrations.DeleteModel(
            name='SuspectReviewAction',
        ),
    ]
