# Generated by Django 6.0.2 on 2026-02-26 22:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_casesuspect_bail_gateway_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesuspect',
            name='identified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
