from django.urls import path
from .views import (
    CaseReportView,
    AssignedCasesListView,
    CaseSuspectCreateUpdateView,
    IntenseTrackingSuspectsListView,
    ComplainantDetailView,
    CaseWitnessDetailView,
    RewardTipDetailView,
    UserDetailView,
    SuspectCandidateListView,
    InvestigationActionListCreateView,
    DetectiveBoardLayoutView,
    DetectiveBoardStateView,
    DetectiveBoardRelationCreateView,
    DetectiveBoardRelationDeleteView,
    DetectiveBoardNoteCreateView,
    DetectiveBoardNoteDeleteView,
    DetectiveBoardNoteReorderView,
    SergeantBailCandidatesView,
    CaseSuspectBailOfferView,
    MyBailOffersView,
    CaseSuspectBailPayView,
    CaseSuspectBailPayVerifyView,
)

urlpatterns = [
    path('cases/assigned/',        AssignedCasesListView.as_view(),         name='investigation-assigned-cases'),
    path('cases/<int:pk>/',        CaseReportView.as_view(),                name='investigation-case-report'),

    path('suspects/',              CaseSuspectCreateUpdateView.as_view(),   name='investigation-suspect-create'),
    path('suspect-candidates/',    SuspectCandidateListView.as_view(),      name='investigation-suspect-candidates'),
    path('suspects/intense-tracking/', IntenseTrackingSuspectsListView.as_view(), name='investigation-suspect-intense-tracking'),
    path('actions/', InvestigationActionListCreateView.as_view(), name='investigation-actions'),
    path('bail/sergeant-candidates/', SergeantBailCandidatesView.as_view(), name='investigation-bail-sergeant-candidates'),
    path('bail/my/', MyBailOffersView.as_view(), name='investigation-bail-my'),
    path('suspects/<int:pk>/',     CaseSuspectCreateUpdateView.as_view(),   name='investigation-suspect-update'),
    path('suspects/<int:pk>/bail-offer/', CaseSuspectBailOfferView.as_view(), name='investigation-suspect-bail-offer'),
    path('suspects/<int:pk>/bail-pay/', CaseSuspectBailPayView.as_view(), name='investigation-suspect-bail-pay'),
    path('suspects/<int:pk>/bail-pay/verify/', CaseSuspectBailPayVerifyView.as_view(), name='investigation-suspect-bail-pay-verify'),
    path('board-layout/<int:case_id>/', DetectiveBoardLayoutView.as_view(), name='investigation-board-layout'),
    path('board-state/<int:case_id>/', DetectiveBoardStateView.as_view(), name='investigation-board-state'),
    path('board-relations/', DetectiveBoardRelationCreateView.as_view(), name='investigation-board-relation-create'),
    path('board-relations/<int:pk>/', DetectiveBoardRelationDeleteView.as_view(), name='investigation-board-relation-delete'),
    path('board-notes/', DetectiveBoardNoteCreateView.as_view(), name='investigation-board-note-create'),
    path('board-notes/<int:pk>/', DetectiveBoardNoteDeleteView.as_view(), name='investigation-board-note-delete'),
    path('board-notes/reorder/', DetectiveBoardNoteReorderView.as_view(), name='investigation-board-note-reorder'),

    path('complainants/<int:pk>/', ComplainantDetailView.as_view(),         name='investigation-complainant'),
    path('witnesses/<int:pk>/',    CaseWitnessDetailView.as_view(),         name='investigation-witness'),
    path('tips/<int:pk>/',         RewardTipDetailView.as_view(),           name='investigation-tip'),
    path('users/<int:pk>/',        UserDetailView.as_view(),                name='investigation-user'),
]
